# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13sfNK7XN3GcYbynRQJJdALXx1NtBEmB-
"""

import pandas as pd

df = pd.read_csv("/content/sample_data/real_estate_bangalore_area_prices.csv", parse_dates=['date'])

cagr = (
    df.groupby('area')
    .apply(lambda x: (x['avg_price_per_sqft'].iloc[-1] / x['avg_price_per_sqft'].iloc[0]) ** (1/10) - 1)
    .reset_index(name='CAGR')
)

cagr['CAGR_%'] = (cagr['CAGR'] * 100).round(2)
cagr

import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))
for area in df['area'].unique():
    subset = df[df['area'] == area]
    plt.plot(subset['date'], subset['avg_price_per_sqft'], label=area)

plt.title("Bangalore Real Estate Price Evolution (2015–2025)")
plt.xlabel("Year")
plt.ylabel("Avg Price per Sqft (INR)")
plt.legend()
plt.grid(True)
plt.show()

yoy_summary = (
    df.groupby(['area','year'])['yoy_pct']
    .mean()
    .reset_index()
)

covid = df[df['year'].between(2019, 2021)]

covid.groupby(['area','year'])['avg_price_per_sqft'].mean().reset_index()

!pip install streamlit
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# -------------------------------
# Page Config
# -------------------------------
st.set_page_config(
    page_title="Bangalore Real Estate Analytics",
    layout="wide"
)

# -------------------------------
# Load Data
# -------------------------------
@st.cache_data
def load_data():
    df = pd.read_csv(
        "/content/sample_data/real_estate_bangalore_area_prices.csv",
        parse_dates=["date"]
    )
    return df

df = load_data()

# Ensure 'year' column exists (in case it's not in CSV)
if 'year' not in df.columns:
    df['year'] = df['date'].dt.year

# -------------------------------
# Sidebar Filters
# -------------------------------
st.sidebar.title("Filters")

areas = st.sidebar.multiselect(
    "Select Areas",
    options=df['area'].unique(),
    default=df['area'].unique()
)

year_range = st.sidebar.slider(
    "Select Year Range",
    int(df['year'].min()),
    int(df['year'].max()),
    (2015, 2025)
)

filtered_df = df[
    (df['area'].isin(areas)) &
    (df['year'] >= year_range[0]) &
    (df['year'] <= year_range[1])
]

if filtered_df.empty:
    st.warning("No data for selected filters. Adjust the year range or areas.")
    st.stop()

# -------------------------------
# Title
# -------------------------------
st.title("📊 Bangalore Real Estate Price Evolution (2015–2025)")
st.markdown(
    "An interactive analysis of residential price trends across major Bangalore micro-markets."
)

# -------------------------------
# KPI Metrics
# -------------------------------
col1, col2, col3 = st.columns(3)

with col1:
    latest_year = filtered_df['year'].max()
    latest_df = filtered_df[filtered_df['year'] == latest_year]
    avg_2025 = int(latest_df['avg_price_per_sqft'].mean()) if not latest_df.empty else 0
    st.metric(
        f"Average Price ({latest_year})",
        f"₹{avg_2025:,}/sqft"
    )

with col2:
    # Protect against single-row areas
    growths = []
    for area in areas:
        area_df = filtered_df[filtered_df['area'] == area].sort_values('date')
        if len(area_df) > 1:
            g = (area_df['avg_price_per_sqft'].iloc[-1] /
                 area_df['avg_price_per_sqft'].iloc[0] - 1) * 100
            growths.append(g)
    total_growth = sum(growths) / len(growths) if growths else 0
    st.metric("Avg Growth (selected period)", f"{total_growth:.1f}%")

with col3:
    st.metric("Areas Analyzed", len(areas))

# -------------------------------
# Price Trend Chart
# -------------------------------
st.subheader("📈 Price Trend by Area")

fig, ax = plt.subplots(figsize=(10, 5))
for area in areas:
    area_df = filtered_df[filtered_df['area'] == area].sort_values('date')
    ax.plot(
        area_df['date'],
        area_df['avg_price_per_sqft'],
        marker='o',
        label=area
    )

ax.set_xlabel("Year")
ax.set_ylabel("Avg Price per Sqft (₹)")
ax.legend()
ax.grid(True)
plt.xticks(rotation=45)
st.pyplot(fig)

# -------------------------------
# 1) Historical CAGR (return proxy)
# -------------------------------
st.subheader("🚀 Long-Term Growth (CAGR %)")

# Assume roughly 10-year horizon based on min/max date
cagr_df = (
    df[df['area'].isin(areas)]
    .sort_values(['area', 'date'])
    .groupby('area')
    .apply(
        lambda x: ((x['avg_price_per_sqft'].iloc[-1] /
                    x['avg_price_per_sqft'].iloc[0]) ** (1/10) - 1) * 100
                 if len(x) > 1 else 0
    )
    .reset_index(name='CAGR_%')
)

fig, ax = plt.subplots(figsize=(8, 4))
ax.bar(cagr_df['area'], cagr_df['CAGR_%'])
ax.set_ylabel("CAGR % (≈2015–2025)")
ax.set_title("Historical Return by Area")
ax.grid(axis='y')
plt.xticks(rotation=45)
st.pyplot(fig)

st.dataframe(cagr_df, use_container_width=True)

# -------------------------------
# 2) Volatility (risk proxy)
# -------------------------------
st.subheader("⚠️ Price Volatility (Risk)")

# Compute YoY % change if not present
if 'yoy_pct' not in df.columns:
    df = df.sort_values(['area', 'date'])
    df['yoy_pct'] = (
        df.groupby('area')['avg_price_per_sqft']
        .pct_change() * 100
    )

volatility_df = (
    df[df['area'].isin(areas)]
    .groupby('area')['yoy_pct']
    .std()
    .reset_index(name='Volatility')
)

fig, ax = plt.subplots(figsize=(8, 4))
ax.bar(volatility_df['area'], volatility_df['Volatility'])
ax.set_ylabel("Std Dev of YoY %")
ax.set_title("Market Risk by Area")
ax.grid(axis='y')
plt.xticks(rotation=45)
st.pyplot(fig)

st.dataframe(volatility_df, use_container_width=True)

# -------------------------------
# 3) Risk–Return Matrix (where to invest)
# -------------------------------
st.subheader("💼 Risk–Return Matrix (Next 10Y Signal)")

investment_df = cagr_df.merge(volatility_df, on='area')

fig, ax = plt.subplots(figsize=(7, 5))
ax.scatter(
    investment_df['Volatility'],
    investment_df['CAGR_%'],
    s=200
)

for _, row in investment_df.iterrows():
    ax.text(
        row['Volatility'],
        row['CAGR_%'],
        row['area'],
        fontsize=9,
        ha='center',
        va='bottom'
    )

ax.set_xlabel("Risk (Volatility of YoY %)")
ax.set_ylabel("Return (CAGR %)")
ax.set_title("Areas Positioned for Next 10 Years")
ax.grid(True)
st.pyplot(fig)

st.markdown("""
- Focus on areas with **high CAGR %** and **moderate volatility** for long-term wealth creation.
- Highly volatile but high-CAGR areas suit aggressive investors; low-CAGR low-risk areas suit conservative investors.
- Use this matrix to shortlist 2–3 micro-markets for deeper deal-level analysis over the next decade.
""")
